### ISSUE TITLE
MD_MAX72xx_PrintText example does not work with ESP8266

### ISSUE THREAD

**Issue by biohazardxxx** [MajicDesigns/MD_MAX72XX#1]
Hi,
does the library support ESP8266? Example MD_MAX72xx_PrintText.ino compiles and uplooads fine but the text does not show correctly.
Any hint?

Best regards
-Bio

**Comment by MajicDesigns** [comment]
Can you please give me more details?
- What ESP8266 setup?
- Which pins have you connected for SPI?
- What does "text does not show correct;ly" mean? Do you see nothing, something, what?

**Comment by biohazardxxx** [comment]
Yes I see something but not readable characters .The H is kind of ok but the rest not.

![image](https://cloud.githubusercontent.com/assets/1370362/20610099/426fd818-b295-11e6-8abc-957cf84efafb.png)

The xx_Test sketch works fine but also not the text. 

Another library  [MAX7219LedMatrix](https://github.com/squix78/MAX7219LedMatrix) works fine but that is not powerfull like this one with Parola.

I've an ESP03 connected like this:

|LED Matrix |	ESP8266                     |
|-----------|-----------------------------|
|VCC        |	+3.3V                       |
|GND	      | GND                         |
|DIN	      |GPIO13 (HSPID)               |
|CS	        |GPIO2 |
|CLK	      |GPIO14 (HSPICLK)             |

**Comment by MajicDesigns** [comment]
Look like you may not have selected the right hardware type in the main header file. All the matrices are wired in different ways so you need to set one of the USE_*_HW by editing the file depending on your type of hardware.

**Comment by biohazardxxx** [comment]
You are of course right. It work super awesome now!
 I am sorry, you even wrote on the main readme: "This is the most asked support question".
Maybe make it bold to increase the chance people read it?
Many thanks for this great work!
