### ISSUE TITLE
Default Arduino SPI Library incompatiable

### ISSUE THREAD

**Issue by MikeDash** [MajicDesigns/MD_MAX72XX#10]
The newest version 2.9.1 requires SPI.h, however the default SPI library of Arduino doesn't include the SPI methods used by the library, and thus won't build.

Build errors for:
SPI.beginTransaction 
SPI.endTransaction

V2.6 compiles, and runs great.

**Comment by MajicDesigns** [comment]
SPI library documentation says otherwise. What OS and ide version are you using?

**Comment by MikeDash** [comment]
Sorry, the new version just required that I remove the old version first.  
It is working great!  Very well coded, and documented.

**Comment by MajicDesigns** [comment]
No problems. Good that it was solved.
