### ISSUE TITLE
Changing font squirts an integer at the serial port

### ISSUE THREAD

**Issue by m1dst** [MajicDesigns/MD_MAX72XX#10]
Currently when switching between fonts triggers a number such as 5 or 7 to be written to the serial port.  Could this be disabled as it is causing unwanted traffic?  I took a brief look at the source but couldn't find the culprit.

**Comment by MajicDesigns** [comment]
Please see closed issue #8

**Comment by wabbitguy** [comment]
@MajicDesigns - I just used the Arduino to update to 3.0.1 and that bug is still in the code. Then I deleted the MD_MAX library and installed 3.0.1 via the Library Manager. Where ever it's pulling the code from, it's got the Serial.print(max) still in there.

**Comment by MajicDesigns** [comment]
Try 3.0.2 - it is as up-to-date as possible now.

**Comment by wabbitguy** [comment]
@MajicDesigns That did it Marco! Thanks!
