### ISSUE TITLE
is there a way to do vertical flip ?

### ISSUE THREAD

**Issue by tavdog** [MajicDesigns/MD_MAX72XX#11]
I'm wondering if there is a way to flip the display vertically in software.  I accidentally installed my display upside down ;(

**Comment by MajicDesigns** [comment]
Use transform() with the parameter.

TFUD | Transform Flip Up to Down.

**Comment by tavdog** [comment]
Thanks. I also found the FLIP_UD effect in Parola. I am using MD_Parola also.  Better to use the Parola effect than transform ?

**Comment by MajicDesigns** [comment]
Depends what you are doing.
If you are working in Parola, the use the Parola syntax.
If you are using MD_MAX72xx on its own then use its own syntax.
But don't mix them up.

**Comment by tavdog** [comment]
Thank you for the lightning fast response !
