### ISSUE TITLE
Printing Swe characters

### ISSUE THREAD

**Issue by bortek** [MajicDesigns/MD_MAX72XX#13]
Apologies before I start writing this question. Might sound trivial but I am looking a simple way to print öäåÖÄÅ (swedish) characters on 8x8 LED (MAX7219) .

Let's say if I take MD_MAX72XX_PrintText from examples and replace output text with this

char message[BUF_SIZE] = {"HelloÅ"};

then I get a "Hello |-" instead of HelloÅ

How in an easy can this be achieved ? 

Surely I am not the first one who have asked as these characters are common in many european languages. But I cannot find a readily available solution.

**Comment by MajicDesigns** [comment]
You probably should look at the UTF8 example in the Parola library. EVen if you are not using Parola, the character mapping concepts and algorithm will apply.

Also, refer to closed issue #6.

**Comment by bortek** [comment]
I looked at the example you are referring to and tried to run it but still could not get umlaut characters to display. 

I was thinking more that there should have been a support in the underlying libraries so that when typing a text with umlauts in the code it should be displayed on the matrix.

**Comment by MajicDesigns** [comment]
Always welcome contribution from users. If you extend the libraries in that way for your own use please submit it for review and inclusion in a future release.

**Comment by bortek** [comment]
thanks. Will do.
