### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by ieee488** [MajicDesigns/MD_MAX72XX#14]
I don't pretend to know how Github works

The link to MD_MAX72xx.h  on https://majicdesigns.github.io/MD_MAX72XX/page_software.html  is broken

All the links on https://majicdesigns.github.io/MD_MAX72XX/files.html  are broken

All the links on https://majicdesigns.github.io/MD_MAX72XX/globals.html   are broken

.

**Comment by MajicDesigns** [comment]
If you have the library installed you should have a duplicate of this doc in the MD_MAX72XX/docs folder (open index.html). Local version works on my system - does it work locally for you?

**Comment by ieee488** [comment]
Yes, the local version works.

The online version is broken.

**Comment by MajicDesigns** [comment]
Looks like this is a problem broken for every other repository as well. I'll note it but can't understand what to do about it for the moment.
