### ISSUE TITLE
A small error in the line of example "eyes"

### ISSUE THREAD

**Issue by Cesar-S** [MajicDesigns/MD_MAX72XX#16]
Hi, there is an error in the `MD_MAX72xx_Eyes.ino` example, in the following line, "eye =" instead of "M ="
````
//MD_MAX72XX eye = MD_MAX72XX(HARDWARE_TYPE, DATA_PIN, CLK_PIN, CS_PIN, MAX_DEVICES);
````
regards.

**Comment by MajicDesigns** [comment]
Thanks. Corrected and will be issued in the next update.
