### ISSUE TITLE
expected unqualified-id

### ISSUE THREAD

**Issue by dinands** [MajicDesigns/MD_MAX72XX#17]
good evening
sorry for this but am very new to this hobby,
but keep holding this error what am I doing wrong.
again sorry .
greeting Dinand

MD_MAX72xx.h:258:1: error: expected unqualified-id before 'class'

 class MD_MAX72XX

 ^

MD_MAX72xx.h:258:1: error: expected constructor, destructor, or type conversion before 'class'

exit status 1
expected unqualified-id before 'class'

**Comment by MajicDesigns** [comment]
I have just compiled MD_MAX72xx_Test.ino from the example programs and it does not show this error. Can you explain what you are doing and your environment (Windows/Linux) and version of the IDE.

**Comment by dinands** [comment]
😟sorry problem solft
