### ISSUE TITLE
Possible to change font

### ISSUE THREAD

**Issue by johneakin** [MajicDesigns/MD_MAX72XX#20]
How is it possible to change the font?
The default seems to be very straight number, I want the numbers more rounded.

How can I configure the LCD5x7_fixed_single font to be used?

Thanks

**Comment by MajicDesigns** [comment]
1. Make sure you read the library documentation. This is in the docs folder, open index.html.
2. Read the blog posts at arduinoplusplus.wordpress.com. Search for "Parola A to Z" and read the relevant articles. These are also linked from the Parola library documentation if you are using MD_Parola.
