### ISSUE TITLE
How to revert to old font.

### ISSUE THREAD

**Issue by tavdog** [MajicDesigns/MD_MAX72XX#22]
After updating I see the default font has changed.  How do I revert to the old font with the updated version ? Thanks.

**Comment by MajicDesigns** [comment]
In MD_MAX72xx_font.cpp change "#define USE_NEW_FONT 1" to value of 0.

**Comment by tavdog** [comment]
Thank you so much.  Here a few images of my project using the MAX7219.  
<img width="623" alt="Screen Shot 2019-07-20 at 20 Sat 11 52 37 AM" src="https://user-images.githubusercontent.com/8324295/61584539-2797c000-aae5-11e9-8ea1-1447af01a727.png">
<img width="441" alt="Screen Shot 2019-07-20 at 20 Sat 11 52 29 AM" src="https://user-images.githubusercontent.com/8324295/61584540-2797c000-aae5-11e9-80b3-f4993a2db48f.png">
<img width="494" alt="Screen Shot 2019-07-20 at 20 Sat 11 52 18 AM" src="https://user-images.githubusercontent.com/8324295/61584541-28305680-aae5-11e9-85bc-a560cea0bcdf.png">
<img width="275" alt="Screen Shot 2019-07-20 at 20 Sat 11 52 09 AM" src="https://user-images.githubusercontent.com/8324295/61584542-28305680-aae5-11e9-8c94-2547c9a2fba9.png">

**Comment by tavdog** [comment]
There was no integer definition of USE_NEW_FONT so instead I just commented out the #define USE_NEW_FONT statement and this works.
