### ISSUE TITLE
getPoint was not declared within this scope

### ISSUE THREAD

**Issue by ExileFox** [MajicDesigns/MD_MAX72XX#27]
![image](https://user-images.githubusercontent.com/2000703/71566895-96793c00-2abb-11ea-9048-0ad112d05760.png)

## Your Environment
**Library Version: latest today** 
**Arduino IDE version: 1.8.10** 
**Hardware model/type: single generic 8x8** 

## Steps to Reproduce
Put getPoint somewhere in your code. it will not compile anymore

**Comment by MajicDesigns** [comment]
What sketch are you compiling?

**Comment by MajicDesigns** [comment]
The function prototype is in the header file and the function is defined in the class file.

Your code snippet does referencing the object name. The correct invocation is <object>.getPoint().

**Comment by ExileFox** [comment]
Was in a bit of a rush and missed that.
