### ISSUE TITLE
MD_MAX72xx_Message_Serial example does not load characters > 127

### ISSUE THREAD

**Issue by pkoronawa** [MajicDesigns/MD_MAX72XX#28]
## Subject of the issue
MD_MAX72xx_Message_Serial example does not load characters > 127

## Steps to Reproduce
Include the degree symbol (\220) in a message string.

## Expected Behaviour
Degree character scrolled out

## Actual Behaviour
Garbage bits scroll out

This is due to line 98 in scrollDataSource. char *p loads a negative value and indexes the font table incorrectly. I fixed it locally by casting (uint8_t)*p++.

**Comment by MajicDesigns** [comment]
Example has been fixed.
