### ISSUE TITLE
Add to PlatformIO registry?

### ISSUE THREAD

**Issue by bkhofmann** [MajicDesigns/MD_MAX72XX#3]
Is it possible to get this library added to the PlatformIO Registry like some of your others?

**Comment by MajicDesigns** [comment]
As far as I know, this is the ONLY library that should be on PlatformIO because a forked version was on but not updating version. Point me to the registration process and I'll investigate.

**Comment by bkhofmann** [comment]
[http://docs.platformio.org/en/latest/userguide/lib/cmd_register.html](url)

Appears it may need to be done within the PlatformIO software.  I'm pretty new to this!

**Comment by bkhofmann** [comment]
[http://docs.platformio.org/en/latest/librarymanager/creating.html](url)

Here's another link as well.

**Comment by MajicDesigns** [comment]
You are correct that PlatformIO registration requires the use of PlatformIO. As I do not use PLatformIO (nor do I intent to start at this stage), this is not going to happen by me. It does not stop others registering the MD_* libraries if they want to, as the _library.properties_ manifest file is sufficient for PlatformIO to register the libraries.
