### ISSUE TITLE
Custom Sprites

### ISSUE THREAD

**Issue by ChopsKingsland** [MajicDesigns/MD_MAX72XX#31]
Does anyone know how to display custom sprites on the MAX7219 using the MD_MAX72xx and MD_PAROLA libraries?

**Comment by MajicDesigns** [comment]
None of the MD_Parola examples using sprites help?

**Comment by ChopsKingsland** [comment]
No, because I don't really understand how they work...

**Comment by ChopsKingsland** [comment]
![image](https://user-images.githubusercontent.com/18499854/90828234-96bd9480-e335-11ea-96fe-3c7e7269e60c.png)

I did find this program that someone wrote, but that uses the LedControl library

**Comment by MajicDesigns** [comment]
Might be useful to read the article “Parola A to Z – Sprite Text Effects” on my blog site arduinoplusplus.wordpress.com

**Comment by ChopsKingsland** [comment]
Is there anyway to do it so the sprite just stays on the matrix, and isn't a text effect?

**Comment by MajicDesigns** [comment]
Load it column by column using MD_MAX72XX. With Parola it assumes you will do animations.

**Comment by ChopsKingsland** [comment]
How do I load my 'pattern' column by column?

**Comment by MajicDesigns** [comment]
Pretty much the way that your example code works except that you store and load a column instead of a row.

**Comment by ChopsKingsland** [comment]
Is there any examples of this, and how do I convert my pattern to columns?

**Comment by MajicDesigns** [comment]
Every sprite example stores by column and the article describes it that way.

**Comment by ChopsKingsland** [comment]
I edited the 'sprites_simple' example, and it works, but that is still animating the text in, whereas I want one panel to just display a sprite

**Comment by MajicDesigns** [comment]
Great, so you know how to create a sprite bitmap.

If you use Parola, then the sprite will animate. You may be able to just print the sprite as a character by crating a custom character with your same bitmap and printing that to the display, but there is no in-place animation.

If you use MD_MAX72xx, then, as I said before, you need to read the data and display it one column at a time. There is no automatic way to do this. Have you looked at the Pacman example?

**Comment by ChopsKingsland** [comment]
How can I create a custom character, as I don't fully understand how the Pacman example works?

**Comment by MajicDesigns** [comment]
Once again, there is a CustomChars example in Parola that you should be able to follow.

It would be a lot more productive for you if you read some of the documentation available and for the library as many of your questions are covered in there. There are also many examples, as you probably already see\n, that show how to do things but you need to become more confident to just try things to see if they work.

You may also find it easier and quicker to get handholding help in the Arduino forum (arduino.cc), where there are a lot more people who can answer the questions and also in your time zone.

**Comment by MajicDesigns** [comment]
Close due to inactivity
