### ISSUE TITLE
Should  INTENSITY=0 mean LEDS are off?  

### ISSUE THREAD

**Issue by WheresWally** [MajicDesigns/MD_MAX72XX#4]
Hi, I am using the library to drive the $5 4x 8x8 LED matrix and love that it works so well.
I kinda thought that    mx.control(MD_MAX72XX::INTENSITY, 0);
would mean the LEDS be blank.
Is that correct?
Terry

**Comment by MajicDesigns** [comment]
Sets it to minimum intensity, which depends on your resistors driving the max7219. Use shutdown() to cut the power.

**Comment by WheresWally** [comment]
Popped the LED matrix off, there is a 10K current limit resistor.
So off to the data sheet to see.
Here is a pic of one of the drivers [http://i.imgur.com/r6NZy72.jpg](url)

**Comment by WheresWally** [comment]
The LED is a 1088AS 20mA max FWD current.. FWD V of 2.1-2.5V
So the Rset for it would be more like 27K.
10k means a 40mA max current which is too much for that LED module.

**Comment by WheresWally** [comment]
from the datasheet it seems 1/16 is the loweest PWM, so it cant do blank via the intensity register.

_Digital control of display brightness is provided by an
internal pulse-width modulator, which is controlled by
the lower nibble of the intensity register. The modulator
scales the average segment current in 16 steps from a
maximum of 31/32 down to 1/32 of the peak current set
by RSET (15/16 to 1/16 on MAX7221). Table 7 lists the
intensity register format. The minimum interdigit blanking
time is set to 1/32 of a cycle._

**Comment by MajicDesigns** [comment]
Yes, that is the problem with the modules. My Parola modules use 68k for minimum current requirements. You can string together a lot more modules that way as well.
