### ISSUE TITLE
Issue when using >32 devices

### ISSUE THREAD

**Issue by LEdgeley** [MajicDesigns/MD_MAX72XX#4]
I have a string of 40 MAX7219 controlled matrices which I'm attempting to control using an Arduino Mega 2560 R3 and the MD_MAX72XX library.

I've used the print_test sample code to get my matrices to display a string of characters ("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"). Everything works correctly as I change MAX_DEVICES to values in the range 1-32 (as expected, the sequence repeats when the physical string of matrices is longer than MAX_DEVICES):
![dsc_1017](https://user-images.githubusercontent.com/5224599/36604508-cc3c68f4-18b5-11e8-96ca-e076cdc5bc2a.JPG)

However, when I change MAX_DEVICES to a value >32, the subsequent matrices are not controlled.

MAX_DEVICES = 33:
![dsc_1018](https://user-images.githubusercontent.com/5224599/36604521-d3a60474-18b5-11e8-80ba-91425378e9d6.JPG)

MAX_DEVICES = 36:

![dsc_1019](https://user-images.githubusercontent.com/5224599/36604549-e64a040e-18b5-11e8-9657-6ab0b271f491.JPG)

MAX_DEVICES = 40: 

![dsc_1020](https://user-images.githubusercontent.com/5224599/36604554-e9c6f1be-18b5-11e8-9640-295d36ee178a.JPG)

**Comment by MajicDesigns** [comment]
> the sequence repeats when the physical string of matrices is longer than MAX_DEVICES

This is true only if you send more than once, but I get what you are saying.

Can you please provide more information:
1. How are these matrices wired?
2. What is the power supply (I assume external, but please confirm).
3. Please post the code you are using.

**Comment by MajicDesigns** [comment]
Before we go too much further, can you try the latest upload of the library. The column number parameter to setColumn() was uint8_t instead of uint16_t. 32 modules just happens to be 256 columns, so would  overflow the uint8_t. Let me know the result.

**Comment by LEdgeley** [comment]
Just tried the new version, and it wouldn't compile - missing a semicolon on line 315 of MD_MAX72xx.h.

However, once I added in the missing semicolon the new version works perfectly on 40 devices. Sadly I don't have 8192 modules to test the new upper bound!

Thanks so much for your fix.

**Comment by MajicDesigns** [comment]
Thanks.
