### ISSUE TITLE
Question about scan limit

### ISSUE THREAD

**Issue by tapir** [MajicDesigns/MD_MAX72XX#43]
This is a question rather then a bug report. Feel free to delete/close if you feel like this is not the place.

I have a led matrix with 4 columns (DIG0-DIG1) and 8 rows. I'm trying to disable the unused 4 columns however I'm not sure what I should set SCANLIMIT to as the maximum number it can have looks like is 7 thus making me feel that the number does not correlate directly with the number of digits/columns that one wants to have enabled.

Any pointer would be appreciated. Thanks.

**Comment by MajicDesigns** [comment]
In The MAX72xx chips, the scan limit is the last 'digit' that is scanned (not the number of rows), so 0 is the lowest and 7 is the highest (ie, you will always scan at least digit 0).

Whether setScanLimit() works the way you expect depends on how the digits are mapped to rows or columns in the matrix module you are using (see this blog article https://arduinoplusplus.wordpress.com/2017/04/14/parola-a-to-z-adapting-for-different-hardware/). The MD_MAX72xx_Test example sketch (around line 402 - function scanLimit()) includes a test of the scan limit functionality - running this will show you whether rows or columns are blanked out as the scanned digits are progressively restricted.
