### ISSUE TITLE
The bar chart does not use one row

### ISSUE THREAD

**Issue by Permutor** [MajicDesigns/MD_MAX72XX#5]
I noticed that the bar chart does not use one row.
It can be easily fixed with simple updates in both 'case 2' sections:
      case 2: 
        curPoint = random(9)-1 ; 
        break;

and:
      case 2:   // bar chart
        if (curPoint<=-1){
          curCol=255;
        }
        else {
           for (uint8_t i=0; i<8; i++)
             curCol |= (i<=curPoint ? 0 : 1) << i;
        }
        break;

**Comment by MajicDesigns** [comment]
Fixed by changing:
      case 2:   // bar chart
        for (uint8_t i=0; i<8; i++)
          curCol |= (i < curPoint ? 0 : 1) << i;
        break;
