### ISSUE TITLE
string specular and polarity reverse per char

### ISSUE THREAD

**Issue by intel2004** [MajicDesigns/MD_MAX72XX#5]
i try your library in arduino nano,all the exaple sketch look the same:
every single chars is reversed and in specular position.an imagine can explain here is print_text example:

![img_20180330_210939](https://user-images.githubusercontent.com/28896329/38150435-1ecccff4-345f-11e8-9589-adbad6eea81f.jpg)

**Comment by MajicDesigns** [comment]
Did you change the MD_MAX72xx library to tell it which hardware you are using? Please follow the instructions in the library documentation if you have not already done so?

**Comment by intel2004** [comment]
i found it:
change MD_MAX72xx_lib.h , line 483 like that:

#if USE_PAROLA_HW   // tested MC 8 March 2014
//#pragma message "PAROLA HW selected"
#define HW_DIG_ROWS 1 ///< MAX72xx digits are mapped to rows in on the matrix
#define HW_REV_COLS 0 ///< Normal orientation is col 0 on the right. Set to 1 if reversed
#define HW_REV_ROWS 0 ///< Normal orientation is row 0 at the top. Set to 1 if reversed
#endif

with that is ok, i try to put these define on scketch but not send the parameters

**Comment by MajicDesigns** [comment]
Actually the instructions say to change the defines in the MD_MAX72xx.h file.
