### ISSUE TITLE
Can i store messages that i send from web browser to internal memory Wemos Mini?

### ISSUE THREAD

**Issue by WardanaID** [MajicDesigns/MD_MAX72XX#53]
hello, im using latest library MD MAX72xx version 3.3.0, i have using example sketch MD_MAX72XX_Message_ESP8266 on Wemos D1 mini
when i restart microcontroller, all messages that i send from web browser were back displaying IP address, is there a way to store message in internal memory wemos mini d1 esp8266?

**Comment by MajicDesigns** [comment]
That question is about the specifics of the ESP8266 rather than how the library works. I don't use these processors much so I cannot give you advice about the hardware architecture. You may have better luck at the Arduino forum (Arduino.cc).
