### ISSUE TITLE
Corruption in scrolled text example

### ISSUE THREAD

**Issue by elan** [MajicDesigns/MD_MAX72XX#54]
Scrolling text can leave garbage in-between characters. This is due to the code here:

```c++
    for (uint8_t i=0; i<=charWidth; i++)
    {
      mx.transform(MD_MAX72XX::TSL);
      if (i < charWidth)
        mx.setColumn(0, cBuf[i]);
      delay(DELAYTIME);
    }
```

The correct code should be like this (we need to zero out the row explicitly):

```c++
    for (uint8_t i=0; i<=charWidth; i++)
    {
      mx.transform(MD_MAX72XX::TSL);
      mx.setColumn(0, (i < charWidth) ? cBuf[i] : 0);
      delay(DELAYTIME);
    }
```

Thanks for a great library!

**Comment by MajicDesigns** [comment]
Which example file? (name)

**Comment by elan** [comment]
I apologize for the lack of context: https://github.com/MajicDesigns/MD_MAX72XX/blob/a761e79a2cf29538cbbdb0c0cb0754ac7ddc8612/examples/MD_MAX72xx_Test/MD_MAX72xx_Test.ino#L53-L58

**Comment by MajicDesigns** [comment]
Change will be included in the next release.
