### ISSUE TITLE
Change the orientation of the panels (request)

### ISSUE THREAD

**Issue by marcfon** [MajicDesigns/MD_MAX72XX#8]
I'm using a "4 in 1" 32x8 display module (https://www.aliexpress.com/item/MAX7219-Dot-Matrix-Module-For-Arduino-Microcontroller-4-In-One-Display-with-5P-Line/32616226423.html) based on the MAX7219. The problem is that that modules are not chained from top to bottom but from left to right. So the displays are rotated 90 degrees. Is it possible to change the orientation of the displays through the library? Should I be using HW_REV_COLS and HW_REV_ROWS for that?

**Comment by marcfon** [comment]
Nevermind I probably just need to use the FC-16 module instead of the generic one.

**Comment by MajicDesigns** [comment]
The library allows you to change the orientation of the modules. Please read the extensive documentation that comes with the library.

Whether the entry is on the left or right simply depends on how you physically position the display. One position is 180 degrees with respect to the other.
