### ISSUE TITLE
How can I display special characters, like German umlaut? 

### ISSUE THREAD

**Issue by hildwin** [MajicDesigns/MD_MAX72XX#9]
I'd like to use the library and the ESP8266 example to display special characters, German umlaut, like ä, ö, ü and ß or other special characters like the degree symbol with the MD_MAX7xx and the ESP8266. A "ä" is shown as %C3%A4 on the matrix.

**Comment by MajicDesigns** [comment]
You will need to build an application that uses the technique shown in the ISO8 example with the MD_Parola library.

**Comment by hildwin** [comment]
Thanks, I'll give it a try!
