### ISSUE TITLE
Adapting for Hardware

### ISSUE THREAD

**Issue by ramojirocks** [MajicDesigns/MD_MAX72XX#9]
how to change invertion of letters in led matrix by using md_max72xx.h file

**Comment by ramojirocks** [comment]
we are not getting files of #define USE_PAROLA_HW 0

**Comment by MajicDesigns** [comment]
Please read the library documentation or read this blog post https://arduinoplusplus.wordpress.com/2017/04/14/parola-a-to-z-adapting-for-different-hardware/
